[package]
name = "kvm_dump_live"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
env_logger = "0.9"
clap = "3.0.0-beta.4"
icebox_backend_dumb_dump = {path = "../backends/dumb_dump"}
icebox_backend_kvm = {path = "../backends/kvm"}
