[package]
name = "patch"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]


[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
bytemuck = { version = "1.7", features = ["derive"]}
