[workspace]
members = [
    "backends/dumb_dump",
    "backends/kvm",
    "icebox",
    "icebox_core",
    "icebox_dwarf",
    "kvm-common",
    "os/linux",
    "patch",
    "phys_addr",
]

[profile.dev]
opt-level = 1
