[workspace]
resolver = "2"
members = [
    # "bin/check",
    "bin/force_mmap",
    "bin/kvm_dump_live",
    "icebox",
    "icebox-core",
    "native",
    "patch",
    "python",
]

[profile.dev]
opt-level = 1

[profile.release]
debug = 1
# lto = "thin"
