[package]
name = "kvm_dump_live"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os = "linux")'.dependencies]
icebox = {path = "../../icebox"}

clap = {version = "=3.0.0-rc.3", features = ["derive"]}
env_logger = "0.9"
