[package]
name = "kvm_dump_live"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
clap = { version = "4.0.0", features = ["derive"] }
env_logger = "0.10"


[target.'cfg(target_os = "linux")'.dependencies.icebox]
workspace = true
features = ["kvm", "dump"]
