[package]
name = "icebox"
version = "0.1.0"
edition = "2021"

[features]
default = ["all_os", "object"]
std = ["ibc/std"]

object = ["ibc/object"]

all_os = ["linux"]
linux = []

kvm = ["std", "libc", "anyhow"]
dump = ["std"]

[dependencies]
ibc = {package = "icebox-core", version = "0.1", path = "../icebox-core"}

anyhow = {version = "1.0", optional = true}
bytemuck = {version = "1.7", features = ["derive"]}
hashbrown = "0.11"
libc = {version = "0.2.94", optional = true}
log = "0.4"
memchr = {version = "2.4", default-features = false}
