[package]
name = "icebox"
version = "0.1.0"
edition = "2018"

[features]
default = ["std"]
std = []

[dependencies]
anyhow = "1.0"
bytemuck = {version = "1.7", features = ["derive"]}
gimli = {version = "0.25", features = ["read"]}
hashbrown = {version = "0.11"}
libc = "0.2.94"
log = "0.4"
memchr = {version = "2.4"}
object = {version = "0.27"}
serde = {version = "1.0", features = ["derive"]}
sync_file = "0.2"
