[package]
name = "icebox"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
bytemuck = {version = "1.7", features = ["derive"]}
clap = "3.0.0-beta.4"
env_logger = "0.9"
gimli = {version = "0.25", features = ["read"]}
hashbrown = {version = "0.11"}
libc = "0.2.94"
log = "0.4"
memchr = {version = "2.4"}
object = {version = "0.26"}
serde = {version = "1.0", features = ["derive"]}
kvm = {path = "../kvm"}
