[package]
name = "icebox"
version = "0.1.0"
edition = "2018"

[features]
default = ["icebox_os_linux", "icebox_backend_kvm", "icebox_backend_dumb_dump"]
std = ["icebox_os_linux/std"]

[dependencies]
ibc = {path = "../icebox_core", package = "icebox_core"}

icebox_backend_dumb_dump = {path = "../backends/dumb_dump", optional = true}
icebox_backend_kvm = {path = "../backends/kvm", optional = true}
icebox_os_linux = {path = "../os/linux", optional = true}

anyhow = "1.0"
env_logger = "0.9"
kvm-common = {path = "../kvm-common"}
