[package]
name = "force_mmap"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os = "linux")'.dependencies]
sync_file = "0.2"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.48"
features = [
    "Win32_Foundation",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Memory",
    "Win32_System_Threading",
]
