[package]
name = "icebox-core"
version = "0.1.0"
edition = "2021"

[features]
std = ["gimli/std", "object/std", "sync_file"]
python = ["std", "pyo3"]

[dependencies]
bytemuck = {version = "1.7", features = ["derive"]}
hashbrown = "0.11"
log = "0.4"

object = {version = "0.27", default-features = false, features = ["read_core", "elf"], optional = true}
gimli = {version = "0.26", default-features = false, features = ["read"]}

sync_file = {version = "0.2", optional = true}

pyo3 = {version = "0.15", optional = true}
