[package]
name = "native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["std"]
std = ["icebox/std", "icebox/all_backends", "icebox/windows"]

custom_allocator = []

[dependencies]
icebox = {path = "../icebox", default-features = false, features = ["linux"]}
ibc = {package = "icebox-core", path = "../icebox-core"}

bytemuck = "1.9"
spin = {version = "0.9", default-features = false, features = ["spin_mutex"]}
log = "0.4"

[build-dependencies]
cbindgen = {version = "0.21", default-features = false}
