include_version = true
language = "C"
cpp_compat = true

[defines]
"feature = custom_allocator" = "CUSTOM_ALLOCATOR"
"feature = std" = "STD"

[parse]
parse_deps = true
include = ["vmc", "vminer-core"]

# [parse.expand]
# crates = ["vmc", "vminer-core"]
