[package]
name = "icebox-python"
version = "0.1.0"
edition = "2021"

[lib]
name = "iceboxa"
crate-type = ["cdylib"]

[dependencies]
icebox = {path = "../icebox", features = ["all_backends"]}
icebox-core = {path = "../icebox-core"}

pyo3 = "0.16"
pyo3-log = "0.6"
log = "0.4"
