[package]
name = "vminer_kvm_patch"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]


[target.'cfg(target_os = "linux")'.dependencies]
libc = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }
