[package]
name = "icebox_core"
version = "0.1.0"
edition = "2018"

[features]
std = []

[dependencies]
kvm-common = {path = "../kvm-common"}

bytemuck = {version = "1.7", features = ["derive"]}
hashbrown = {version = "0.11"}
