on: [push, pull_request]

name: CI

env:
  CARGO_INCREMENTAL: 0

jobs:
  check:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - windows-latest
    name: Clippy
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        run: rustup toolchain install stable && rustup default stable

      - run: cargo clippy -- -D warnings

  check-no_std:
    name: Check no_std
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        run: rustup toolchain install stable && rustup default stable && rustup target add aarch64-unknown-none

      - run: cargo check -p icebox --target aarch64-unknown-none --no-default-features

  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: cargo fmt -- --check

  # TODO: Re-enable this when the issue with git LFS is fixed
  test:
    name: Run tests
    if: false
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Get test data
        uses: actions/checkout@v4
        with:
          repository: thalium/icebox2_data
          lfs: true
          path: data
          ssh-key: ${{ secrets.DUMPS_DEPLOY_KEY }}

      - name: Decompress x86_64 dump
        run: zstd -d data/linux-5.10-x86_64/dump.zst -o data/linux-5.10-x86_64/dump

      - name: Decompress aarch64 dump
        run: zstd -d data/linux-5.10-aarch64/dump.zst -o data/linux-5.10-aarch64/dump

      - name: Install toolchain
        run: rustup toolchain install stable && rustup default stable

      - run: cargo test -p icebox --all-features
