on: [push, pull_request]

name: CI

env:
  CARGO_INCREMENTAL: 0

jobs:
  test:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - windows-latest
    name: Check
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: cargo check
        run: cargo check

  check-no_std:
    name: Check no_std
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: aarch64-unknown-none
          toolchain: stable
          override: true

      - name: cargo check
        run: cargo check -p icebox

  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: cargo fmt -- --check
        run: cargo fmt -- --check
